### ISSUE TITLE
feat: 함께해요 제목 + 내용 검색

### ISSUE THREAD

**Issue by why-only-english** [ttoklip/BackEnd#220]
## 🤷 구현할 기능
함께해요 제목 + 내용 검색 기능 구현합니다.

## 🔨 상세 작업 내용
- [x] 제목 + 내용 검색
- [x] url 수정

## 📄 참고 사항
소통해요 검색 참고

**Comment by why-only-english** [comment]
// todo 
Home에서 불러오는 `CartSingleResponse` 사용

**Comment by why-only-english** [comment]
@toychip  지금 함께해요 이외에 다른 도메인들은 제목 검색만 돼서 PM님께 물어보고 다른 도메인도 제목 + 내용 검색으로 수정하면 될 것 같아요 ~~

**Comment by toychip** [comment]
> @toychip 지금 함께해요 이외에 다른 도메인들은 제목 검색만 돼서 PM님께 물어보고 다른 도메인도 제목 + 내용 검색으로 수정하면 될 것 같아요 ~~

아하 넵넵 확인했습니다~
