### ISSUE TITLE
Refactor: HoneyTip Layered architecture -> DDD

### ISSUE THREAD

**Issue by toychip** [ttoklip/BackEnd#248]
## 🤷 구현할 기능
HoneyTIp 도메인 DDD로 변경합니다.

**Comment by toychip** [comment]
@why-only-english 
DDD로 구조를 변경하게 될 경우 연관관계를 모두 해제해야하므로 대공사일 것으로 보입니다. 이는 추후에 하는 걸로 ^^..
기존 MVC를 유지하되, Entity 자체를 도메인으로 두고, 구현체는 infrastructure로 두는 것으로 변경하겠습니다.
참고 자료 : https://velog.io/@byeongju/%EB%A6%AC%ED%8C%A9%ED%86%A0%EB%A7%81-%EB%AF%B8%EC%85%98-step3-%EB%8A%90%EB%82%80%EC%A0%90JPA-DDD

**Comment by why-only-english** [comment]
> @why-only-english DDD로 구조를 변경하게 될 경우 연관관계를 모두 해제해야하므로 대공사일 것으로 보입니다. 이는 추후에 하는 걸로 ^^.. 기존 MVC를 유지하되, Entity 자체를 도메인으로 두고, 구현체는 infrastructure로 두는 것으로 변경하겠습니다. 참고 자료 : https://velog.io/@byeongju/%EB%A6%AC%ED%8C%A9%ED%86%A0%EB%A7%81-%EB%AF%B8%EC%85%98-step3-%EB%8A%90%EB%82%80%EC%A0%90JPA-DDD

작업하느라 고생하셨습니다.. 😿  우리동네 도메인 작업 진행할게요 ~ 👍
